services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
            MYSQL_DATABASE: "flask-crud"
            MYSQL_ROOT_PASSWORD: "admin"
        ports:
            - "3307:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"
        volumes:
            - /home/thiago/rocketseat-python/Modulo_4/mysql:/var/lib/mysql
